from __future__ import annotations

import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

FORBIDDEN_PATH_FRAGMENTS = (
    "port" + "folio",
    "generate_" + "port" + "folio",
    "compose." + "port" + "folio",
    "tools/evidence",
)

FORBIDDEN_TEXT = {
    "presentation term": re.compile(r"\bport" + r"folio\b", re.IGNORECASE),
    "chat assistant name": re.compile(r"\bChat" + r"GPT\b", re.IGNORECASE),
    "vendor name": re.compile(r"\bOpen" + r"AI\b", re.IGNORECASE),
    "machine-generated label": re.compile(r"\bA" + r"I[- ]generated\b", re.IGNORECASE),
    "machine attribution": re.compile(r"\bgenerated by A" + r"I\b", re.IGNORECASE),
}

tracked = subprocess.run(
    ["git", "ls-files"],
    cwd=ROOT,
    check=True,
    text=True,
    capture_output=True,
).stdout.splitlines()

path_failures = [
    path
    for path in tracked
    if any(fragment in path.lower() for fragment in FORBIDDEN_PATH_FRAGMENTS)
]
if path_failures:
    raise SystemExit(
        "Public file names contain presentation-heavy wording:\n"
        + "\n".join(path_failures)
    )

text_failures: list[str] = []
for relative in tracked:
    if relative == "tools/quality/verify_public_metadata.py":
        continue
    path = ROOT / relative
    if not path.is_file():
        continue

    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        continue

    for label, pattern in FORBIDDEN_TEXT.items():
        for match in pattern.finditer(text):
            line = text.count("\n", 0, match.start()) + 1
            text_failures.append(f"{relative}:{line}: {label}")

if text_failures:
    raise SystemExit(
        "Public repository text contains disallowed presentation wording:\n"
        + "\n".join(text_failures)
    )

print("Public repository naming and metadata check passed.")
